apiVersion: v1
kind: Service
metadata:
  name: bocanary
  namespace: bocanary-workload
  labels:
    app.kubernetes.io/name: bocanary
    app.kubernetes.io/instance: flagger
spec:
  type: ClusterIP
  ports:
    - port: 80
  selector:
    app: bocanary