apiVersion: flagger.app/v1beta1
kind: Canary
metadata:
  name: api-canary
  namespace: naos
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: naos-api
  service:
    port: 80
  analysis:
    # schedule interval (default 60s)
    interval: 10s
    # max number of failed metric checks before rollback
    threshold: 5
    # promotion increment step percentage (0-100)
    stepWeight: 10
    # max traffic percentage routed to canary percentage (0-100)
    maxWeight: 100
    metrics:
    - name: request-success-rate
      thresholdRange:
        min: 99
      interval: 1m
    - name: request-duration
      thresholdRange:
        max: 3000
      interval: 1m