apiVersion: apps/v1
kind: Deployment
metadata:
  name: naos-api
  namespace: naos
spec:
  replicas: 2
  selector:
    matchLabels:
      app: naos-api
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      labels:
        app: naos-api
    spec:
      imagePullSecrets:
      - name: dockerhub
      containers:
      - image: moimhossain/naos-api:v1.0.blue
        imagePullPolicy: Always
        name: naos-api
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 100m
            memory: 100Mi